url: https://chauff.github.io/dir2016
baseurl: /dir2016
# Site settings
title: "#DIR2016"
email: c.hauff@tudelft.nl
description: "Dutch-Belgian Information Retrieval Workshop 2016."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/_DIR2016

# Build settings
markdown: kramdown
permalink: pretty
